component: koa
name: koaDemo
app: koa-demo-e8c46452

inputs:
  runtime: Nodejs12.16
  functionName: ${name}
  entryFile: app.js # 自定义 server 的入口文件名，默认为 sls.js，如果不想修改文件名为 sls.js 可以自定义
  src:
    src: ./
    exclude:
      - .env
  functionConf:
    environment: #  环境变量
      variables: #  环境变量数组
        NODE_ENV: test
  apigatewayConf: #  api网关配置
    enableCORS: true #  允许跨域
    protocols:
      - http
      - https
