component: http
name: koaDemo
inputs:
  src:
    src: ./
    exclude:
      - .env
  faas:
    runtime: Nodejs12.16
    framework: koa
    name: ${name}
  apigw:
    ignoreUpdate: true
    protocols:
      - http
      - https
app: koa-demo-e8c46452
