component: koa
name: koaDemo
app: koaDemoApp
stage: test

inputs:
  runtime: Nodejs12.16
  functionName: ${name}-${stage}-${app}
  entryFile: app.js # 自定义 server 的入口文件名，默认为 sls.js，如果不想修改文件名为 sls.js 可以自定义
  src:
    src: ./
    exclude:
      - .env
  functionConf:
    environment: #  环境变量
      variables: #  环境变量数组
        NODE_ENV: test
  apigatewayConf: #  api网关配置
    enableCORS: true #  允许跨域
    isBase64Encoded: true # 上传文件
    environment: release
    protocols:
      - http
      - https
  layers:
    - name: ${output:${stage}:${app}:MyTestLayer.name} #  layer名称
      version: ${output:${stage}:${app}:MyTestLayer.version} #  版本
